# File: src/main/resources/plugin.yml

name: CatCraft
main: com.soul.catcraft.CatCraft
version: "1.21.8-SNAPSHOT_3"
api-version: "1.20"
api: "1.20"
description: A plugin that protects cats via deterrence. Includes other commands for a more comfortable server control.
author: soulwax
website: https://github.com/soulwax/CatCraft

commands:
  catcraft:
    description: Universal command for CatCraft administration
    usage: "/<command> <msgall|inv|ender|disarm|help|rules|credits> [args...]"
    aliases: [cc]
    permission: catcraft.admin
    permission-message: "You don't have permission to use this command"

  ccw:
    description: Quick whisper function
    usage: "/<command> <player> <message>"
    permission: catcraft.whisper
    permission-message: "You don't have permission to use this command"

  anon:
    description: Send anonymous message (bypasses Discord relay)
    usage: "/<command> <message>"
    permission: catcraft.anonymous
    permission-message: "You don't have permission to use this command"

permissions:
  catcraft.*:
    description: Full CatCraft plugin access
    default: op
    children:
      catcraft.anonymous:
        description: Allows sending anonymous messages (/anon)
        default: true
      catcraft.whisper:
        description: Allows using whisper commands (/ccw, /anon)
        default: true
      catcraft.admin:
        description: Allows using administrative commands (/catcraft, /cc)
        default: op

  chat.format.member:
    description: Default member role in chat
    default: true

  chat.format.moderator:
    description: Moderator role in chat
    default: false

  chat.format.admin:
    description: Admin role in chat
    default: op
