name: CatCraft
main: com.gray17.soul.catcraft.CatCraft
version: 1.17.119
description: A plugin that protects cats via deterrence. Includes other commands for a more comfortable server control.
api-version: 1.17

commands:
  catcraft:
    description: Universal command, features so far are msg, kill, inv, ender, permission, disarm. Alias = cc
    usage: type in '/catcraft(or /cc) help' for a list of available commands
    permission: catcraft.admin
    permission-message: you don't have the permission to use this command
  cc:
    description: Universal command, features so far are msg, kill, inv, ender, permission, disarm.
    usage: type in '/catcraft(or /cc) help' for a list of available commands
    permission: catcraft.admin
    permission-message: you don't have the permission to use this command
  ccw:
    description: Quick whisper function. Follows the following syntax - /ccw <player> <message>
    usage: type in '/catcraft(or /cc) help' for a list of available commands
    permission: catcraft.whisper
    permission-message: you don't have the permission to use this command

permissions:
    chat.*:
        description: Chat formatting
        children:
        chat.format.member: true
        chat.format.moderator: true
        chat.format.admin: true
    chat.format.member:
        description: Default member role in chat.
        default: true
    chat.format.moderator:
        description: Moderator member role in chat.
        default: op
    chat.format.admin:
        description: Highest member role = admin in chat.
        default: false

    catcraft.*:
        description: Allows the user to use CatCraft administrative tools.
        children:
            catcraft.whisper: true
            catcraft.admin: true
        catcraft.whisper:
            description: Allows the player to use the CatCraft Whisper command /ccw <player> <message>
            default: true
        catcraft.admin:
            description: Allows the player to use the CatCraft administrative commands like /inv, /disarm, /ender and so on.
            default: op
        
        
        